# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/jazzband/pip-tools
    rev: v5.1.2
    hooks:
    -   id: pip-compile
        files: ^requirements/prod\.(in|txt)$
        args: [requirements/prod.in, --generate-hashes]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: v5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: v23.10.1
    hooks:
    -   id: black
